/**
 * Mandarin Chinese translations for demo questions.
 * Auto-generated by scripts/translate-questions.ts.
 * Regenerate: npm run translate-questions
 */
export const demoQuestionsZh: Record<string, { questionText: string; choices: { label: string; text: string }[] }> = {
  "pq-e1": {
    "questionText": "80 的 25% 是多少？",
    "choices": [
      {
        "label": "A",
        "text": "15"
      },
      {
        "label": "B",
        "text": "20"
      },
      {
        "label": "C",
        "text": "25"
      },
      {
        "label": "D",
        "text": "40"
      }
    ]
  },
  "pq-e2": {
    "questionText": "350 的 10% 是多少?",
    "choices": [
      {
        "label": "A",
        "text": "3.5"
      },
      {
        "label": "B",
        "text": "35"
      },
      {
        "label": "C",
        "text": "70"
      },
      {
        "label": "D",
        "text": "350"
      }
    ]
  },
  "pq-e3": {
    "questionText": "64 的 50% 是多少？",
    "choices": [
      {
        "label": "A",
        "text": "16"
      },
      {
        "label": "B",
        "text": "28"
      },
      {
        "label": "C",
        "text": "32"
      },
      {
        "label": "D",
        "text": "48"
      }
    ]
  },
  "pq-e4": {
    "questionText": "200 的 75% 是多少?",
    "choices": [
      {
        "label": "A",
        "text": "100"
      },
      {
        "label": "B",
        "text": "125"
      },
      {
        "label": "C",
        "text": "150"
      },
      {
        "label": "D",
        "text": "175"
      }
    ]
  },
  "pq-e5": {
    "questionText": "45 的 20% 是多少?",
    "choices": [
      {
        "label": "A",
        "text": "5"
      },
      {
        "label": "B",
        "text": "9"
      },
      {
        "label": "C",
        "text": "15"
      },
      {
        "label": "D",
        "text": "22.5"
      }
    ]
  },
  "pq-e6": {
    "questionText": "一个班有40名学生。如果30%的学生缺席，那么有多少学生缺席？",
    "choices": [
      {
        "label": "A",
        "text": "8"
      },
      {
        "label": "B",
        "text": "10"
      },
      {
        "label": "C",
        "text": "12"
      },
      {
        "label": "D",
        "text": "28"
      }
    ]
  },
  "pq-e7": {
    "questionText": "600 的 5% 是多少?",
    "choices": [
      {
        "label": "A",
        "text": "3"
      },
      {
        "label": "B",
        "text": "12"
      },
      {
        "label": "C",
        "text": "30"
      },
      {
        "label": "D",
        "text": "120"
      }
    ]
  },
  "pq-cf1": {
    "questionText": "$\\frac{3}{4}$ 用百分比表示是多少？",
    "choices": [
      {
        "label": "A",
        "text": "34%"
      },
      {
        "label": "B",
        "text": "60%"
      },
      {
        "label": "C",
        "text": "75%"
      },
      {
        "label": "D",
        "text": "80%"
      }
    ]
  },
  "pq-cf2": {
    "questionText": "$\\frac{1}{5}$ 作为百分比是多少?",
    "choices": [
      {
        "label": "A",
        "text": "5%"
      },
      {
        "label": "B",
        "text": "15%"
      },
      {
        "label": "C",
        "text": "20%"
      },
      {
        "label": "D",
        "text": "25%"
      }
    ]
  },
  "pq-cf3": {
    "questionText": "$\\frac{2}{5}$ 等于百分之几?",
    "choices": [
      {
        "label": "A",
        "text": "20%"
      },
      {
        "label": "B",
        "text": "25%"
      },
      {
        "label": "C",
        "text": "40%"
      },
      {
        "label": "D",
        "text": "45%"
      }
    ]
  },
  "pq-cf4": {
    "questionText": "把 $\\frac{1}{8}$ 表示为百分比。",
    "choices": [
      {
        "label": "A",
        "text": "8%"
      },
      {
        "label": "B",
        "text": "12.5%"
      },
      {
        "label": "C",
        "text": "15%"
      },
      {
        "label": "D",
        "text": "18%"
      }
    ]
  },
  "pq-cf5": {
    "questionText": "下面哪个百分数等于 $\\frac{7}{10}$？",
    "choices": [
      {
        "label": "A",
        "text": "17%"
      },
      {
        "label": "B",
        "text": "35%"
      },
      {
        "label": "C",
        "text": "70%"
      },
      {
        "label": "D",
        "text": "71%"
      }
    ]
  },
  "pq-cf6": {
    "questionText": "把 $\\frac{1}{3}$ 用百分比表示，四舍五入到最接近的整数是多少？",
    "choices": [
      {
        "label": "A",
        "text": "30%"
      },
      {
        "label": "B",
        "text": "33%"
      },
      {
        "label": "C",
        "text": "35%"
      },
      {
        "label": "D",
        "text": "37%"
      }
    ]
  },
  "pq-fw1": {
    "questionText": "15 是某个数的 25%，这个数是多少？",
    "choices": [
      {
        "label": "A",
        "text": "45"
      },
      {
        "label": "B",
        "text": "60"
      },
      {
        "label": "C",
        "text": "75"
      },
      {
        "label": "D",
        "text": "375"
      }
    ]
  },
  "pq-fw2": {
    "questionText": "42 是某个数的 30%，这个数是多少？",
    "choices": [
      {
        "label": "A",
        "text": "126"
      },
      {
        "label": "B",
        "text": "140"
      },
      {
        "label": "C",
        "text": "1260"
      },
      {
        "label": "D",
        "text": "14"
      }
    ]
  },
  "pq-fw3": {
    "questionText": "一个学生得了36分，这是总分的80%。总分是多少？",
    "choices": [
      {
        "label": "A",
        "text": "40"
      },
      {
        "label": "B",
        "text": "45"
      },
      {
        "label": "C",
        "text": "48"
      },
      {
        "label": "D",
        "text": "50"
      }
    ]
  },
  "pq-fw4": {
    "questionText": "18 是哪个数的 15%?",
    "choices": [
      {
        "label": "A",
        "text": "2.7"
      },
      {
        "label": "B",
        "text": "27"
      },
      {
        "label": "C",
        "text": "120"
      },
      {
        "label": "D",
        "text": "270"
      }
    ]
  },
  "pq-fw5": {
    "questionText": "一家店铺卖出了56件商品，这是其库存的70%。那么这家店铺原来库存了多少件商品？",
    "choices": [
      {
        "label": "A",
        "text": "39"
      },
      {
        "label": "B",
        "text": "72"
      },
      {
        "label": "C",
        "text": "80"
      },
      {
        "label": "D",
        "text": "126"
      }
    ]
  },
  "pq-fw6": {
    "questionText": "9 是某个数的 12.5%，这个数是多少？",
    "choices": [
      {
        "label": "A",
        "text": "1.125"
      },
      {
        "label": "B",
        "text": "36"
      },
      {
        "label": "C",
        "text": "72"
      },
      {
        "label": "D",
        "text": "112.5"
      }
    ]
  },
  "pq-dc1": {
    "questionText": "一份报告显示增长率为 0.045。这用百分比表示是多少？",
    "choices": [
      {
        "label": "A",
        "text": "0.45%"
      },
      {
        "label": "B",
        "text": "4.5%"
      },
      {
        "label": "C",
        "text": "45%"
      },
      {
        "label": "D",
        "text": "450%"
      }
    ]
  },
  "pq-dc2": {
    "questionText": "把 135% 表示成小数。",
    "choices": [
      {
        "label": "A",
        "text": "0.135"
      },
      {
        "label": "B",
        "text": "1.35"
      },
      {
        "label": "C",
        "text": "13.5"
      },
      {
        "label": "D",
        "text": "135.0"
      }
    ]
  },
  "pq-dc3": {
    "questionText": "哪个小数等于 $0.8\\%$？",
    "choices": [
      {
        "label": "A",
        "text": "0.8"
      },
      {
        "label": "B",
        "text": "0.08"
      },
      {
        "label": "C",
        "text": "0.008"
      },
      {
        "label": "D",
        "text": "8.0"
      }
    ]
  },
  "pq-dc4": {
    "questionText": "把 2.5 表示为百分比。",
    "choices": [
      {
        "label": "A",
        "text": "2.5%"
      },
      {
        "label": "B",
        "text": "25%"
      },
      {
        "label": "C",
        "text": "250%"
      },
      {
        "label": "D",
        "text": "0.25%"
      }
    ]
  },
  "pq-dc5": {
    "questionText": "一个概率是 0.003。这是百分之几？",
    "choices": [
      {
        "label": "A",
        "text": "0.003%"
      },
      {
        "label": "B",
        "text": "0.03%"
      },
      {
        "label": "C",
        "text": "0.3%"
      },
      {
        "label": "D",
        "text": "3%"
      }
    ]
  },
  "pq-dc6": {
    "questionText": "把 $\\frac{5}{8}$ 转换成百分比。",
    "choices": [
      {
        "label": "A",
        "text": "58%"
      },
      {
        "label": "B",
        "text": "62.5%"
      },
      {
        "label": "C",
        "text": "65%"
      },
      {
        "label": "D",
        "text": "80%"
      }
    ]
  },
  "pq-rp1": {
    "questionText": "37.5 是 250 的百分之几?",
    "choices": [
      {
        "label": "A",
        "text": "12%"
      },
      {
        "label": "B",
        "text": "15%"
      },
      {
        "label": "C",
        "text": "18%"
      },
      {
        "label": "D",
        "text": "20%"
      }
    ]
  },
  "pq-rp2": {
    "questionText": "一所学校有1{,}200名学生，其中78人打网球。打网球的学生占百分之几？",
    "choices": [
      {
        "label": "A",
        "text": "5.5%"
      },
      {
        "label": "B",
        "text": "6.0%"
      },
      {
        "label": "C",
        "text": "6.5%"
      },
      {
        "label": "D",
        "text": "7.8%"
      }
    ]
  },
  "pq-rp3": {
    "questionText": "一个食谱用了180克面粉，总重量是720克。面粉占百分之几？",
    "choices": [
      {
        "label": "A",
        "text": "18%"
      },
      {
        "label": "B",
        "text": "20%"
      },
      {
        "label": "C",
        "text": "25%"
      },
      {
        "label": "D",
        "text": "30%"
      }
    ]
  },
  "pq-rp4": {
    "questionText": "在360名受访者中，有54人选择了选项A。选择A的百分比是多少？",
    "choices": [
      {
        "label": "A",
        "text": "12%"
      },
      {
        "label": "B",
        "text": "15%"
      },
      {
        "label": "C",
        "text": "18%"
      },
      {
        "label": "D",
        "text": "54%"
      }
    ]
  },
  "pq-rp5": {
    "questionText": "一个学生在76道题中答对了57道。他们的成绩四舍五入到最近的百分比是多少?",
    "choices": [
      {
        "label": "A",
        "text": "72%"
      },
      {
        "label": "B",
        "text": "75%"
      },
      {
        "label": "C",
        "text": "78%"
      },
      {
        "label": "D",
        "text": "80%"
      }
    ]
  },
  "pq-mc1": {
    "questionText": "把 $\\frac{7}{12}$ 表示为百分比，精确到十分位。",
    "choices": [
      {
        "label": "A",
        "text": "56.3%"
      },
      {
        "label": "B",
        "text": "58.3%"
      },
      {
        "label": "C",
        "text": "60.0%"
      },
      {
        "label": "D",
        "text": "71.2%"
      }
    ]
  },
  "pq-mc2": {
    "questionText": "如果某个数的 $\\frac{2}{3}$ 等于 84，那么这个数的 45% 是多少？",
    "choices": [
      {
        "label": "A",
        "text": "37.8"
      },
      {
        "label": "B",
        "text": "50.4"
      },
      {
        "label": "C",
        "text": "56.7"
      },
      {
        "label": "D",
        "text": "63"
      }
    ]
  },
  "pq-mc3": {
    "questionText": "哪个更大：$\\frac{5}{7}$ 还是 72%？",
    "choices": [
      {
        "label": "A",
        "text": "$\\frac{5}{7}$ 更大"
      },
      {
        "label": "B",
        "text": "72% 更大"
      },
      {
        "label": "C",
        "text": "它们相等"
      },
      {
        "label": "D",
        "text": "无法确定"
      }
    ]
  },
  "pq-mc4": {
    "questionText": "把0.0625转换成最简分数，然后表示成百分比。",
    "choices": [
      {
        "label": "A",
        "text": "$\\frac{1}{16}$ = 6.25%"
      },
      {
        "label": "B",
        "text": "$\\frac{1}{16}$ = 6.5%"
      },
      {
        "label": "C",
        "text": "$\\frac{1}{8}$ = 12.5%"
      },
      {
        "label": "D",
        "text": "$\\frac{5}{8}$ = 62.5%"
      }
    ]
  },
  "pq-mc5": {
    "questionText": "从小到大排列：0.38、$\\frac{3}{8}$、37%",
    "choices": [
      {
        "label": "A",
        "text": "37%、0.38、$\\frac{3}{8}$"
      },
      {
        "label": "B",
        "text": "37%、$\\frac{3}{8}$、0.38"
      },
      {
        "label": "C",
        "text": "$\\frac{3}{8}$、37%、0.38"
      },
      {
        "label": "D",
        "text": "0.38、$\\frac{3}{8}$、37%"
      }
    ]
  },
  "pq-ie1": {
    "questionText": "一件衬衫成本 $40。如果价格上升 10%，新价格是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$4"
      },
      {
        "label": "B",
        "text": "$36"
      },
      {
        "label": "C",
        "text": "$44"
      },
      {
        "label": "D",
        "text": "$50"
      }
    ]
  },
  "pq-ie2": {
    "questionText": "一个500人的群体增长了20%。新的人口是多少？",
    "choices": [
      {
        "label": "A",
        "text": "520"
      },
      {
        "label": "B",
        "text": "600"
      },
      {
        "label": "C",
        "text": "700"
      },
      {
        "label": "D",
        "text": "1000"
      }
    ]
  },
  "pq-ie3": {
    "questionText": "一件 $60 的商品价格上涨了 5%。新价格是多少?",
    "choices": [
      {
        "label": "A",
        "text": "$61"
      },
      {
        "label": "B",
        "text": "$63"
      },
      {
        "label": "C",
        "text": "$65"
      },
      {
        "label": "D",
        "text": "$90"
      }
    ]
  },
  "pq-ie4": {
    "questionText": "一个水箱里有200升。加入增加25%的量后，里面一共有多少升？",
    "choices": [
      {
        "label": "A",
        "text": "225"
      },
      {
        "label": "B",
        "text": "240"
      },
      {
        "label": "C",
        "text": "250"
      },
      {
        "label": "D",
        "text": "275"
      }
    ]
  },
  "pq-ie5": {
    "questionText": "一个$3{,}000的薪资增加了15%。新薪资是多少?",
    "choices": [
      {
        "label": "A",
        "text": "$3{,}150"
      },
      {
        "label": "B",
        "text": "$3{,}300"
      },
      {
        "label": "C",
        "text": "$3{,}450"
      },
      {
        "label": "D",
        "text": "$3{,}500"
      }
    ]
  },
  "pq-de1": {
    "questionText": "一件 $50 的夹克打八折。请问打折后的价格是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$10"
      },
      {
        "label": "B",
        "text": "$30"
      },
      {
        "label": "C",
        "text": "$40"
      },
      {
        "label": "D",
        "text": "$45"
      }
    ]
  },
  "pq-de2": {
    "questionText": "一个有800人的小镇失去了其人口的10%。还剩下多少人?",
    "choices": [
      {
        "label": "A",
        "text": "700"
      },
      {
        "label": "B",
        "text": "720"
      },
      {
        "label": "C",
        "text": "780"
      },
      {
        "label": "D",
        "text": "790"
      }
    ]
  },
  "pq-de3": {
    "questionText": "一件 $120 的商品打折 25%。新价格是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$30"
      },
      {
        "label": "B",
        "text": "$80"
      },
      {
        "label": "C",
        "text": "$90"
      },
      {
        "label": "D",
        "text": "$95"
      }
    ]
  },
  "pq-de4": {
    "questionText": "一个水箱能装400加仑。如果漏出了15%，还剩下多少？",
    "choices": [
      {
        "label": "A",
        "text": "340"
      },
      {
        "label": "B",
        "text": "360"
      },
      {
        "label": "C",
        "text": "380"
      },
      {
        "label": "D",
        "text": "385"
      }
    ]
  },
  "pq-de5": {
    "questionText": "一部价值 $200 的手机贬值了 30%。现在值多少钱？",
    "choices": [
      {
        "label": "A",
        "text": "$60"
      },
      {
        "label": "B",
        "text": "$130"
      },
      {
        "label": "C",
        "text": "$140"
      },
      {
        "label": "D",
        "text": "$170"
      }
    ]
  },
  "pq-iw1": {
    "questionText": "一家公司去年有240名员工。员工人数增加了15%。现在有多少名员工？",
    "choices": [
      {
        "label": "A",
        "text": "255"
      },
      {
        "label": "B",
        "text": "264"
      },
      {
        "label": "C",
        "text": "276"
      },
      {
        "label": "D",
        "text": "360"
      }
    ]
  },
  "pq-iw2": {
    "questionText": "一只股票的价格从$80涨到了$92。涨幅百分比是多少?",
    "choices": [
      {
        "label": "A",
        "text": "12%"
      },
      {
        "label": "B",
        "text": "13%"
      },
      {
        "label": "C",
        "text": "15%"
      },
      {
        "label": "D",
        "text": "87%"
      }
    ]
  },
  "pq-iw3": {
    "questionText": "租金原来是 $1{,}200，增加到了 $1{,}350。增加的百分比是多少？",
    "choices": [
      {
        "label": "A",
        "text": "10%"
      },
      {
        "label": "B",
        "text": "11.1%"
      },
      {
        "label": "C",
        "text": "12.5%"
      },
      {
        "label": "D",
        "text": "15%"
      }
    ]
  },
  "pq-iw4": {
    "questionText": "某网站1月有5{,}000名访客，2月有6{,}500名访客。访客数增长的百分比是多少？",
    "choices": [
      {
        "label": "A",
        "text": "15%"
      },
      {
        "label": "B",
        "text": "23%"
      },
      {
        "label": "C",
        "text": "30%"
      },
      {
        "label": "D",
        "text": "130%"
      }
    ]
  },
  "pq-iw5": {
    "questionText": "某个数量增加了40%后，现在是280。原来是多少？",
    "choices": [
      {
        "label": "A",
        "text": "112"
      },
      {
        "label": "B",
        "text": "168"
      },
      {
        "label": "C",
        "text": "200"
      },
      {
        "label": "D",
        "text": "392"
      }
    ]
  },
  "pq-dw1": {
    "questionText": "一辆价值 $20{,}000 的汽车每年贬值 12%。一年后它的价值是多少?",
    "choices": [
      {
        "label": "A",
        "text": "$2{,}400"
      },
      {
        "label": "B",
        "text": "$15{,}000"
      },
      {
        "label": "C",
        "text": "$17{,}600"
      },
      {
        "label": "D",
        "text": "$18{,}800"
      }
    ]
  },
  "pq-dw2": {
    "questionText": "销售额从450个单位下降到360个单位。百分比下降了多少？",
    "choices": [
      {
        "label": "A",
        "text": "10%"
      },
      {
        "label": "B",
        "text": "20%"
      },
      {
        "label": "C",
        "text": "25%"
      },
      {
        "label": "D",
        "text": "90%"
      }
    ]
  },
  "pq-dw3": {
    "questionText": "一个湖的水位从84英尺下降到71.4英尺。下降了百分之几？",
    "choices": [
      {
        "label": "A",
        "text": "12%"
      },
      {
        "label": "B",
        "text": "13%"
      },
      {
        "label": "C",
        "text": "15%"
      },
      {
        "label": "D",
        "text": "18%"
      }
    ]
  },
  "pq-dw4": {
    "questionText": "某个数值下降了35%后，现在是195。原来的数值是多少？",
    "choices": [
      {
        "label": "A",
        "text": "263"
      },
      {
        "label": "B",
        "text": "300"
      },
      {
        "label": "C",
        "text": "330"
      },
      {
        "label": "D",
        "text": "557"
      }
    ]
  },
  "pq-dw5": {
    "questionText": "入学人数从 1{,}600 下降到 1{,}280。下降的百分比是多少？",
    "choices": [
      {
        "label": "A",
        "text": "15%"
      },
      {
        "label": "B",
        "text": "20%"
      },
      {
        "label": "C",
        "text": "25%"
      },
      {
        "label": "D",
        "text": "80%"
      }
    ]
  },
  "pq-sc1": {
    "questionText": "一个价格先上升20%，然后下降20%。净百分比变化是多少？",
    "choices": [
      {
        "label": "A",
        "text": "0%"
      },
      {
        "label": "B",
        "text": "-2%"
      },
      {
        "label": "C",
        "text": "-4%"
      },
      {
        "label": "D",
        "text": "+4%"
      }
    ]
  },
  "pq-sc2": {
    "questionText": "一只股票在周一上升了10%，在周二又上升了10%。从原始价格开始，总的百分比增长是多少？",
    "choices": [
      {
        "label": "A",
        "text": "20%"
      },
      {
        "label": "B",
        "text": "21%"
      },
      {
        "label": "C",
        "text": "22%"
      },
      {
        "label": "D",
        "text": "110%"
      }
    ]
  },
  "pq-sc3": {
    "questionText": "一个量先减少了10%，然后又增加了20%。净变化是多少？",
    "choices": [
      {
        "label": "A",
        "text": "+8%"
      },
      {
        "label": "B",
        "text": "+10%"
      },
      {
        "label": "C",
        "text": "+12%"
      },
      {
        "label": "D",
        "text": "+30%"
      }
    ]
  },
  "pq-sc4": {
    "questionText": "人口每十年增长50%,连续两个十年。总增长百分比是多少?",
    "choices": [
      {
        "label": "A",
        "text": "100%"
      },
      {
        "label": "B",
        "text": "115%"
      },
      {
        "label": "C",
        "text": "125%"
      },
      {
        "label": "D",
        "text": "150%"
      }
    ]
  },
  "pq-sc5": {
    "questionText": "价格上升了 25%，然后打了 40% 的折扣。净百分比变化是多少？",
    "choices": [
      {
        "label": "A",
        "text": "-15%"
      },
      {
        "label": "B",
        "text": "-20%"
      },
      {
        "label": "C",
        "text": "-25%"
      },
      {
        "label": "D",
        "text": "+15%"
      }
    ]
  },
  "pq-ov1": {
    "questionText": "打完20%的折扣后，一台笔记本电脑的价格是$680。原价是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$800"
      },
      {
        "label": "B",
        "text": "$816"
      },
      {
        "label": "C",
        "text": "$850"
      },
      {
        "label": "D",
        "text": "$880"
      }
    ]
  },
  "pq-ov2": {
    "questionText": "玛丽亚加薪15%后，月收入为$4{,}600。她之前的月薪是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$3{,}910"
      },
      {
        "label": "B",
        "text": "$4{,}000"
      },
      {
        "label": "C",
        "text": "$4{,}100"
      },
      {
        "label": "D",
        "text": "$5{,}290"
      }
    ]
  },
  "pq-ov3": {
    "questionText": "一辆车贬值了35%，现在的价值是$19{,}500。这辆车原来的价值是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$26{,}325"
      },
      {
        "label": "B",
        "text": "$28{,}000"
      },
      {
        "label": "C",
        "text": "$30{,}000"
      },
      {
        "label": "D",
        "text": "$55{,}714"
      }
    ]
  },
  "pq-ov4": {
    "questionText": "加上12%的税后，总金额是$112。税前金额是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$98.56"
      },
      {
        "label": "B",
        "text": "$100"
      },
      {
        "label": "C",
        "text": "$99.12"
      },
      {
        "label": "D",
        "text": "$86.15"
      }
    ]
  },
  "pq-ov5": {
    "questionText": "一家公司员工数增长了60%后，现在有400名员工。问这家公司最初有多少名员工？",
    "choices": [
      {
        "label": "A",
        "text": "160"
      },
      {
        "label": "B",
        "text": "240"
      },
      {
        "label": "C",
        "text": "250"
      },
      {
        "label": "D",
        "text": "340"
      }
    ]
  },
  "pq-tt1": {
    "questionText": "一顿饭花费 $25。你留下 20% 的小费。小费是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$3"
      },
      {
        "label": "B",
        "text": "$4"
      },
      {
        "label": "C",
        "text": "$5"
      },
      {
        "label": "D",
        "text": "$7.50"
      }
    ]
  },
  "pq-tt2": {
    "questionText": "一件商品购价为 $60，需要缴纳 8% 的销售税。税金是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$4.80"
      },
      {
        "label": "B",
        "text": "$6.00"
      },
      {
        "label": "C",
        "text": "$8.00"
      },
      {
        "label": "D",
        "text": "$48.00"
      }
    ]
  },
  "pq-tt3": {
    "questionText": "一份 $15 的午餐要加上 15% 的小费。小费是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$1.50"
      },
      {
        "label": "B",
        "text": "$2.25"
      },
      {
        "label": "C",
        "text": "$3.00"
      },
      {
        "label": "D",
        "text": "$15.15"
      }
    ]
  },
  "pq-tt4": {
    "questionText": "一件商品的价格是 $80，加上 5% 的税。总价是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$80.05"
      },
      {
        "label": "B",
        "text": "$84"
      },
      {
        "label": "C",
        "text": "$85"
      },
      {
        "label": "D",
        "text": "$120"
      }
    ]
  },
  "pq-sd1": {
    "questionText": "一双鞋原价是 $90，打三折。请问降价后的价格是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$27"
      },
      {
        "label": "B",
        "text": "$60"
      },
      {
        "label": "C",
        "text": "$63"
      },
      {
        "label": "D",
        "text": "$70"
      }
    ]
  },
  "pq-sd2": {
    "questionText": "一本书原价 $45，打 10% 折扣。你需要支付多少钱？",
    "choices": [
      {
        "label": "A",
        "text": "$4.50"
      },
      {
        "label": "B",
        "text": "$35"
      },
      {
        "label": "C",
        "text": "$40.50"
      },
      {
        "label": "D",
        "text": "$41"
      }
    ]
  },
  "pq-sd3": {
    "questionText": "一家店铺对一件150美元的夹克衫打四折。你能省下多少钱?",
    "choices": [
      {
        "label": "A",
        "text": "$40"
      },
      {
        "label": "B",
        "text": "$50"
      },
      {
        "label": "C",
        "text": "$60"
      },
      {
        "label": "D",
        "text": "$110"
      }
    ]
  },
  "pq-sd4": {
    "questionText": "一台价格为 $200 的电视打 15% 折扣。请问售价是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$30"
      },
      {
        "label": "B",
        "text": "$170"
      },
      {
        "label": "C",
        "text": "$175"
      },
      {
        "label": "D",
        "text": "$185"
      }
    ]
  },
  "pq-ttt1": {
    "questionText": "一张 $75 的餐费账单，需要加上 8% 的税和 20% 的小费（小费按税前金额计算）。总金额是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$93.00"
      },
      {
        "label": "B",
        "text": "$95.25"
      },
      {
        "label": "C",
        "text": "$96.00"
      },
      {
        "label": "D",
        "text": "$102.00"
      }
    ]
  },
  "pq-ttt2": {
    "questionText": "一件 $120 的购物加上 6.5% 的销售税。总金额是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$126.50"
      },
      {
        "label": "B",
        "text": "$127.80"
      },
      {
        "label": "C",
        "text": "$128.00"
      },
      {
        "label": "D",
        "text": "$186.00"
      }
    ]
  },
  "pq-ttt3": {
    "questionText": "一群人分摊 $180，其中包含 7% 的税（税前基础上加 18% 的小费）。如果平均分给 4 个人，每个人需要付多少钱？",
    "choices": [
      {
        "label": "A",
        "text": "$45.00"
      },
      {
        "label": "B",
        "text": "$50.40"
      },
      {
        "label": "C",
        "text": "$56.25"
      },
      {
        "label": "D",
        "text": "$58.50"
      }
    ]
  },
  "pq-ttt4": {
    "questionText": "一顿 $50 的餐食要加上 9% 的税和 15% 的小费（小费按未税金额计算）。总共要付多少钱？",
    "choices": [
      {
        "label": "A",
        "text": "$60.50"
      },
      {
        "label": "B",
        "text": "$62.00"
      },
      {
        "label": "C",
        "text": "$64.50"
      },
      {
        "label": "D",
        "text": "$68.70"
      }
    ]
  },
  "pq-std1": {
    "questionText": "一件原价 $100 的商品打八折，然后再用一张优惠券在折扣价基础上再打九折。你最后要付多少钱？",
    "choices": [
      {
        "label": "A",
        "text": "$70"
      },
      {
        "label": "B",
        "text": "$72"
      },
      {
        "label": "C",
        "text": "$80"
      },
      {
        "label": "D",
        "text": "$90"
      }
    ]
  },
  "pq-std2": {
    "questionText": "先打七折，再对折后的价格打八折。这跟直接打五折一样吗？",
    "choices": [
      {
        "label": "A",
        "text": "是的，两种方式最后价格一样"
      },
      {
        "label": "B",
        "text": "不是，分次打折会便宜一些"
      },
      {
        "label": "C",
        "text": "不是，分次打折会贵一些"
      },
      {
        "label": "D",
        "text": "取决于原价是多少"
      }
    ]
  },
  "pq-std3": {
    "questionText": "一件 $250 的商品：先打 15% 折扣，再打额外 10% 折扣。最终价格是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$187.50"
      },
      {
        "label": "B",
        "text": "$191.25"
      },
      {
        "label": "C",
        "text": "$200.00"
      },
      {
        "label": "D",
        "text": "$212.50"
      }
    ]
  },
  "pq-std4": {
    "questionText": "一件商品原价 $400，先打 25% 折扣，再打 20% 折扣。最终价格是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$200"
      },
      {
        "label": "B",
        "text": "$220"
      },
      {
        "label": "C",
        "text": "$240"
      },
      {
        "label": "D",
        "text": "$260"
      }
    ]
  },
  "pq-mm1": {
    "questionText": "一家店铺以 $60 的价格进货，以 $90 的价格出售。那么利润率是多少？",
    "choices": [
      {
        "label": "A",
        "text": "30%"
      },
      {
        "label": "B",
        "text": "33.3%"
      },
      {
        "label": "C",
        "text": "50%"
      },
      {
        "label": "D",
        "text": "150%"
      }
    ]
  },
  "pq-mm2": {
    "questionText": "一家店铺以 $60 的价格进货，以 $90 的价格出售。利润率是多少?",
    "choices": [
      {
        "label": "A",
        "text": "30%"
      },
      {
        "label": "B",
        "text": "33.3%"
      },
      {
        "label": "C",
        "text": "50%"
      },
      {
        "label": "D",
        "text": "66.7%"
      }
    ]
  },
  "pq-mm3": {
    "questionText": "某商品的标价比成本高60%。如果成本是$75，那么售价是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$105"
      },
      {
        "label": "B",
        "text": "$112.50"
      },
      {
        "label": "C",
        "text": "$120"
      },
      {
        "label": "D",
        "text": "$135"
      }
    ]
  },
  "pq-mm4": {
    "questionText": "一种产品售价为 $200，利润率为 40%。成本是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$80"
      },
      {
        "label": "B",
        "text": "$120"
      },
      {
        "label": "C",
        "text": "$140"
      },
      {
        "label": "D",
        "text": "$160"
      }
    ]
  },
  "pq-cd1": {
    "questionText": "一件$300的商品打25%折扣，然后在折扣后的价格上加8%的税。总价是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$225.00"
      },
      {
        "label": "B",
        "text": "$243.00"
      },
      {
        "label": "C",
        "text": "$249.00"
      },
      {
        "label": "D",
        "text": "$324.00"
      }
    ]
  },
  "pq-cd2": {
    "questionText": "一台电视的原价是$500，打七折后还要加7%的税。竞争对手店的价格是$380，加上7%的税。哪家店便宜，便宜多少？",
    "choices": [
      {
        "label": "A",
        "text": "第一家店便宜，便宜$32.10"
      },
      {
        "label": "B",
        "text": "第二家店便宜，便宜$33.15"
      },
      {
        "label": "C",
        "text": "第二家店便宜，便宜$31.50"
      },
      {
        "label": "D",
        "text": "价格相同"
      }
    ]
  },
  "pq-cd3": {
    "questionText": "你有一张打8折的优惠券和一张减$15的优惠券，可以用来购买一件$120的商品（折扣后需要加6%的税）。哪种方式能得到最低的总价？",
    "choices": [
      {
        "label": "A",
        "text": "先打8折，再减$15"
      },
      {
        "label": "B",
        "text": "先减$15，再打8折"
      },
      {
        "label": "C",
        "text": "两种方式的总价相同"
      },
      {
        "label": "D",
        "text": "只使用8折优惠券"
      }
    ]
  },
  "pq-cd4": {
    "questionText": "一件 $180 的商品：先打八折，再打八五折，最后加上 9% 的税。最终价格是多少？",
    "choices": [
      {
        "label": "A",
        "text": "$122.47"
      },
      {
        "label": "B",
        "text": "$133.43"
      },
      {
        "label": "C",
        "text": "$140.40"
      },
      {
        "label": "D",
        "text": "$144.00"
      }
    ]
  }
};
